# Custom Language File for Launcher Customizer

[ejs.app]
title = "FalconCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://launcher.falconcraft.it"
mediaTwitterURL = "#"
mediaInstagramURL = "https://www.instagram.com/falconcraft.launcher/"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/3bv4tHRzgd"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU FALCONCRAFT LAUNCHER"
welcomeDescription = "Sei a pochi passi da FalconCraft Launcher"
welcomeDescCTA = "Copyright © 2025 FalconCraft Launcher"
